on:
    workflow_dispatch:
      inputs:
        port_payload:
          required: true
          description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
          type: string
jobs: 
    scaffold:
      runs-on: ubuntu-latest
      steps:
        - uses: port-labs/cookiecutter-gha@v1.1
          with:
            portClientId: ${{ secrets.PORT_CLIENT_ID }}
            portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
            token: ${{ secrets.ORG_TOKEN }}
            portRunId: ${{ fromJson(inputs.port_payload).context.runId }}
            repositoryName: ${{ fromJson(inputs.port_payload).payload.properties.name }}
            portUserInputs: ${{ toJson(fromJson(inputs.port_payload).payload.properties) }} 
            cookiecutterTemplate: https://github.com/lacion/cookiecutter-golang
            blueprintIdentifier: 'microservice'
            organizationName: zajk